# Generated by Django 5.1.3 on 2024-11-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securityapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacktable',
            old_name='USER',
            new_name='USERNAME',
        ),
    ]
